version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8

  build:
    commands:
      - aws cloudfront create-invalidation --distribution-id "E3NH532ONWH97D" --paths "/*"

artifacts:
  files: "**/*"
  exclude_buildspec: true
